import ureaFertilizer from './urear'
import npkFertilizer from './npkfert'
import whowearehome from './whowearehome'
import seedlings from './seedlings'
import chemicals from './agrochem'
import services from './services'
import vision from './vision'
import gallery from './gallery'
import socials from './social'
import partners from './partners'
import aboutus from './aboutus'
import aboutushistory from './aboutushistory'
import aboutusvalues from './aboutusvalues'
import contactus from './contactus'
import post from './post'
import author from './author'
import blockContent from './blockContent'
import category from './category'
import comment from './comment'
import posts2 from './posts2'
import products from './products'

export const schemaTypes = [whowearehome,products,gallery,services,vision,aboutus,ureaFertilizer,npkFertilizer,seedlings,chemicals,aboutushistory,aboutusvalues,partners,socials,contactus,posts2,author,category,blockContent]
